// Browser-only contribution. Syntax remains available without rust-analyzer.
export default {
  async activate(host) {
    return await host.registerLanguage({
      id: "rust",
      extensions: [".rs"],
      configuration: {
        comments: { lineComment: "//", blockComment: ["/*", "*/"] },
        brackets: [
          ["{", "}"],
          ["[", "]"],
          ["(", ")"],
        ],
        autoClosingPairs: [
          { open: "{", close: "}" },
          { open: "[", close: "]" },
          { open: "(", close: ")" },
          { open: '"', close: '"' },
        ],
      },
      monarch: {
        defaultToken: "",
        tokenPostfix: ".rust",
        keywords: [
          "as",
          "async",
          "await",
          "break",
          "const",
          "continue",
          "crate",
          "dyn",
          "else",
          "enum",
          "extern",
          "false",
          "fn",
          "for",
          "if",
          "impl",
          "in",
          "let",
          "loop",
          "match",
          "mod",
          "move",
          "mut",
          "pub",
          "ref",
          "return",
          "self",
          "Self",
          "static",
          "struct",
          "super",
          "trait",
          "true",
          "type",
          "unsafe",
          "use",
          "where",
          "while",
        ],
        tokenizer: {
          root: [
            [/\/\*/, "comment", "@comment"],
            [/\/\/.*$/, "comment"],
            [/"/, "string", "@string"],
            [/'(?:\\.|[^'\\])'/, "string"],
            [/'[a-zA-Z_]\w*/, "type.identifier"],
            [/\b(?:u|i)(?:8|16|32|64|128|size)\b|\b(?:bool|char|str|f32|f64)\b/, "type"],
            [/[a-zA-Z_]\w*!/, "function"],
            [
              /[a-zA-Z_]\w*/,
              {
                cases: { "@keywords": "keyword", "@default": "identifier" },
              },
            ],
            [
              /\b(?:0[xob][\da-fA-F_]+|\d[\d_]*(?:\.\d[\d_]*)?)(?:[ui](?:8|16|32|64|128|size)|f(?:32|64))?\b/,
              "number",
            ],
            [/[{}()[\]]/, "@brackets"],
            [/[=><!~?:&|+*/^%-]+/, "operator"],
            [/[;,.]/, "delimiter"],
          ],
          comment: [
            [/\/\*/, "comment", "@push"],
            [/\*\//, "comment", "@pop"],
            [/[^/*]+|[/*]/, "comment"],
          ],
          string: [
            [/\\./, "string.escape"],
            [/"/, "string", "@pop"],
            [/[^\\"]+/, "string"],
          ],
        },
      },
    });
  },
};
