import { discover } from "@fathom/server";
import type { PluginDef } from "@fathom/sdk";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

/**
 * Generate docs/reference/sdk.md and docs/reference/plugins.md from the code.
 * `--check` exits non-zero when the committed files are stale.
 */

const root = resolve(import.meta.dirname!, "..");
const check = Deno.args.includes("--check");

const ENTRIES = [
  ["@fathom/sdk", "packages/sdk/src/mod.ts"],
  ["@fathom/sdk/ui", "packages/sdk/src/ui/mod.ts"],
] as const;

interface DocSymbol {
  name: string;
  declarations: { kind: string; jsDoc?: { doc?: string } }[];
}

async function sdkReference(): Promise<string> {
  const output = await new Deno.Command(Deno.execPath(), {
    args: ["doc", "--json", ...ENTRIES.map(([, path]) => path)],
    cwd: root,
    stdout: "piped",
    stderr: "inherit",
  }).output();

  if (!output.success) {
    throw new Error("deno doc failed");
  }

  const json = JSON.parse(new TextDecoder().decode(output.stdout)) as {
    nodes: Record<string, { symbols: DocSymbol[] }>;
  };

  const lines = [
    "# SDK reference",
    "",
    "Generated by `deno task docs` from the JSDoc on each export. Edit the",
    "source comment, not this file.",
  ];

  for (const [specifier, path] of ENTRIES) {
    const module = json.nodes[pathToFileURL(resolve(root, path)).href];

    lines.push(
      "",
      `## \`${specifier}\``,
      "",
      "| Export | Kind | Summary |",
      "| --- | --- | --- |",
    );

    for (const symbol of module.symbols) {
      const declaration = symbol.declarations[0];
      const summary = (declaration.jsDoc?.doc ?? "")
        .split(/\n\s*\n/)[0]
        .replaceAll("\n", " ")
        .replaceAll("|", "\\|")
        .trim();

      lines.push(`| \`${symbol.name}\` | ${declaration.kind} | ${summary} |`);
    }
  }

  return lines.join("\n") + "\n";
}

async function pluginReference(): Promise<string> {
  const lines = [
    "# Bundled plugins",
    "",
    "Generated by `deno task docs` from each plugin's backend definition: the",
    "tokens it requires and provides, and its configuration schema.",
  ];

  const plugins = (await discover(root, `${root}/.no-home`)).filter(
    (plugin) => plugin.manifest.backend,
  );

  for (const plugin of plugins) {
    const entry = resolve(plugin.source, "..", plugin.manifest.backend!);
    const module = (await import(pathToFileURL(entry).href)) as {
      default: PluginDef;
    };
    const def = module.default;
    const ids = (tokens: Record<string, { id: string }>) =>
      Object.values(tokens)
        .map((token) => `\`${token.id}\``)
        .join(", ") || "none";

    lines.push(
      "",
      `## ${def.id}`,
      "",
      `- Requires: ${ids(def.requires)}`,
      `- Provides: ${ids(def.provides)}`,
      "",
      "```json",
      JSON.stringify(def.config, null, 2),
      "```",
    );
  }

  return lines.join("\n") + "\n";
}

const outputs: [string, string][] = [
  ["docs/reference/sdk.md", await sdkReference()],
  ["docs/reference/plugins.md", await pluginReference()],
];

let stale = false;

for (const [path, content] of outputs) {
  const target = resolve(root, path);
  const current = await Deno.readTextFile(target).catch(() => "");

  if (current === content) {
    continue;
  }

  if (check) {
    console.error(`${path} is stale; run deno task docs`);
    stale = true;
  } else {
    await Deno.writeTextFile(target, content);
    console.log(`wrote ${path}`);
  }
}

if (stale) {
  Deno.exit(1);
}
